require 'sinatra'
require 'slim'
require 'slim/include'

require_relative 'security'
require_relative 'base'
require_relative 'user'
require_relative 'authentication'
require_relative 'register'
require_relative 'urls'
require_relative '../helpers/helper.rb'